../sim/cf.scs
/opt/cadence/XCELIUM1803/tools/affirma_ams/etc/dms/EE_pkg.sv
/opt/cadence/XCELIUM1803/tools/affirma_ams/etc/connect_lib/*.svams
/opt/cadence/XCELIUM1803/tools/affirma_ams/etc/connect_lib/*.vams
/opt/cadence/XCELIUM1803/tools/affirma_ams/etc/dms/EE_pkg_examples/C*.sv
/opt/cadence/XCELIUM1803/tools/affirma_ams/etc/dms/EE_pkg_examples/I*.sv
/opt/cadence/XCELIUM1803/tools/affirma_ams/etc/dms/EE_pkg_examples/R*.sv
/opt/cadence/XCELIUM1803/tools/affirma_ams/etc/dms/EE_pkg_examples/V*.sv
/opt/cadence/XCELIUM1803/tools/affirma_ams/etc/dms/EE_pkg_examples/ECapG.vams
/opt/cadence/XCELIUM1803/tools/affirma_ams/etc/dms/EE_pkg_examples/EVRsrc.vams
../dut/dms/*.sv
../dut/vams/*.vams
../dut/bind/*.sv
